[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "miniha"
version = "0.1.0"
dependencies = [
    "click==8.1.8",
    "influxdb==5.3.2",
    "matplotlib==3.9.4",
    "numpy==2.0.2",
    "paho-mqtt==2.1.0",
    "pandas==2.3.2",
    "rich",
    "flask",
    "pyyaml",
    "daikinapi",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["miniha"]
namespaces = false


[project.scripts]
miniha_webapp = "miniha.webapp:main" 
mqtt_to_influx = "miniha.mqtt_to_influx:main"
daikin_to_influx = "miniha.daikin_to_influx:main"
daikin_to_influx_v2 = "miniha.daikin_to_influx_v2:main"
influxcli = "miniha.influx_cli:main"
dashboard = "miniha.dashboard:main"