[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "miniha"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "click==8.1.8",
    "influxdb==5.3.2",
    "matplotlib==3.9.4",
    "numpy==2.0.2",
    "scipy>=1.13",
    "paho-mqtt==2.1.0",
    "pandas==2.3.2",
    "rich",
    "flask",
    "pyyaml",
    "daikinapi",
    "streamlit>=1.58.0",
    "plotly>=6.7.0",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["miniha"]
namespaces = false

[tool.pytest.ini_options]
testpaths = ["tests"]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
]


[project.scripts]
miniha_webapp = "miniha.webapp:main" 
mqtt_to_influx = "miniha.mqtt_to_influx:main"
daikin_to_influx = "miniha.daikin_to_influx:main"
daikin_to_influx_v2 = "miniha.daikin_to_influx_v2:main"
open_meteo_to_influx = "miniha.open_meteo_feed:main"
influxcli = "miniha.influx_cli:main"
dashboard = "miniha.dashboard:main"
